/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./App.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./types/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "on-tertiary-fixed": "#1f1c00",
        "background": "#fbf9f9",
        "surface-dim": "#dbdad9",
        "on-primary-container": "#b9baff",
        "surface-variant": "#e3e2e2",
        "tertiary-fixed-dim": "#d2c966",
        "on-secondary-fixed-variant": "#7f0087",
        "tertiary-fixed": "#efe67f",
        "tertiary-container": "#b6ae4e",
        "on-primary-fixed-variant": "#3d3f83",
        "error": "#ba1a1a",
        "primary-container": "#45478b",
        "inverse-primary": "#c0c1ff",
        "on-primary-fixed": "#100f56",
        "on-secondary": "#ffffff",
        "tertiary": "#666000",
        "outline-variant": "#c7c5d2",
        "secondary": "#a311ae",
        "primary": "#2e2f72",
        "on-error-container": "#93000a",
        "inverse-surface": "#303031",
        "on-surface-variant": "#464650",
        "on-secondary-container": "#6c0073",
        "on-error": "#ffffff",
        "surface-bright": "#fbf9f9",
        "secondary-fixed": "#ffd6f9",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#f5f3f3",
        "error-container": "#ffdad6",
        "on-surface": "#1b1c1c",
        "surface-container-highest": "#e3e2e2",
        "surface": "#ffffff",
        "on-background": "#1b1c1c",
        "surface-container": "#efeded",
        "on-tertiary-container": "#454100",
        "on-primary": "#ffffff",
        "primary-fixed": "#e1e0ff",
        "secondary-container": "#f86dfd",
        "surface-tint": "#55579d",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#4d4800",
        "outline": "#777681",
        "inverse-on-surface": "#f2f0f0",
        "on-secondary-fixed": "#37003b",
        "secondary-fixed-dim": "#ffa9fb"
      }
    },
  },
  plugins: [],
};


