import React, { useState } from 'react';

export type LegalTab = 'terms' | 'privacy' | 'medical';

interface LegalModalProps {
    isOpen: boolean;
    initialTab: LegalTab;
    onClose: () => void;
}

const LegalModal: React.FC<LegalModalProps> = ({ isOpen, initialTab, onClose }) => {
    const [activeTab, setActiveTab] = useState<LegalTab>(initialTab);

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[150] flex flex-col w-full h-full bg-[#f5f5f7] text-[#1d1d1f] font-sans">
            <header className="sticky top-0 left-0 right-0 z-10 px-4 py-4 flex items-center justify-between border-b border-gray-200 bg-[#f5f5f7]/90 backdrop-blur-md">
                <div className="flex gap-4">
                    <button 
                        onClick={() => setActiveTab('terms')}
                        className={`text-sm font-bold ${activeTab === 'terms' ? 'text-[#1d1d1f] underline decoration-2 underline-offset-4' : 'text-gray-400'}`}
                    >
                        Terms
                    </button>
                    <button 
                        onClick={() => setActiveTab('privacy')}
                        className={`text-sm font-bold ${activeTab === 'privacy' ? 'text-[#1d1d1f] underline decoration-2 underline-offset-4' : 'text-gray-400'}`}
                    >
                        Privacy
                    </button>
                    <button 
                        onClick={() => setActiveTab('medical')}
                        className={`text-sm font-bold ${activeTab === 'medical' ? 'text-[#1d1d1f] underline decoration-2 underline-offset-4' : 'text-gray-400'}`}
                    >
                        Disclaimer
                    </button>
                </div>
                <button onClick={onClose} className="p-2 bg-black/5 hover:bg-black/10 rounded-full">
                    <svg className="w-5 h-5 text-[#1d1d1f]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </header>

            <main className="flex-1 overflow-y-auto p-6 text-sm text-gray-700 leading-relaxed font-serif pb-24">
                {activeTab === 'terms' && (
                    <div className="space-y-5">
                        <h1 className="text-3xl font-extrabold text-black mb-2">Terms of Service (EULA)</h1>
                        <p className="text-xs text-gray-500 uppercase tracking-widest border-b pb-4 mb-6">Last Updated: April 2026</p>
                        
                        <div className="bg-gray-100 p-4 rounded-lg border border-gray-200">
                            <strong>IMPORTANT NOTICE:</strong> Please read these Terms of Service carefully. By accessing or using Skinface AI, you agree to be bound by these terms. If you do not agree, you must immediately uninstall and cease using the application.
                        </div>

                        <h2 className="text-xl font-bold text-black mt-6">1. Age Restrictions and COPPA Compliance</h2>
                        <p>Skinface AI provides advanced cosmetic, aesthetic, and facial geometric scoring. Due to the psychological intricacies associated with physical assessments, you must be <strong>at least EIGHTEEN (18) years of age</strong> to use this service. By using the app, you warrant that you are legally considered an adult in your jurisdiction. We do not knowingly collect information from children under the age of 18 in compliance with the Children's Online Privacy Protection Act (COPPA).</p>

                        <h2 className="text-xl font-bold text-black mt-6">2. Subscriptions, Payments, and Apple/Google EULA</h2>
                        <p>Skinface AI offers premium subscription plans ("Elite Features"). Payments will be charged to your iTunes or Google Play account at confirmation of purchase. <strong>Subscriptions automatically renew</strong> unless auto-renew is turned off at least 24-hours before the end of the current period.</p>
                        <p><strong>Cancellations & Refunds:</strong> You may cancel your subscription at any time through your Apple ID or Google Play Store settings. Because transactions are processed strictly by Apple and Google, Skinface AI cannot and does not issue direct refunds for unused portions of a billing cycle. Refunds are strictly subject to Apple/Google's App Store policies.</p>

                        <h2 className="text-xl font-bold text-black mt-6">3. Artificial Intelligence Limitations & Fallibility</h2>
                        <p>The aesthetic insights, symmetry scores, and recommended skincare routines are generated by Third-Party Large Language Models (LLM) and Computer Vision pipelines (e.g., Google Gemini, MediaPipe). Artificial Intelligence can produce "hallucinations," inaccuracies, or unpredictable outputs.</p>
                        <p>Therefore, Skinface AI does not warrant the clinical or factual accuracy of any AI-generated metric. Any personal care, grooming, or skincare routines recommended by the app are algorithmic suggestions. <strong>You solely assume the risk</strong> of allergic reactions or undesirable results if you choose to implement these routines.</p>

                        <h2 className="text-xl font-bold text-black mt-6">4. Limitation of Liability</h2>
                        <p className="uppercase text-xs font-semibold leading-relaxed">
                            To the maximum extent permitted by applicable law, Skinface AI, its developers, directors, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages (including medical or psychological distress) resulting from your access to or use of the application. The app is provided on an "AS-IS" and "AS-AVAILABLE" basis without warranties of any kind.
                        </p>

                        <h2 className="text-xl font-bold text-black mt-6">5. Intellectual Property</h2>
                        <p>All algorithms, interfaces, codebases, and trademarks are the exclusive property of Skinface AI. You are explicitly prohibited from reverse-engineering, scraping, or utilizing the face-mesh technology logic for competing purposes.</p>
                    </div>
                )}

                {activeTab === 'privacy' && (
                    <div className="space-y-5">
                        <h1 className="text-3xl font-extrabold text-black mb-2">Privacy & Data Policy</h1>
                        <p className="text-xs text-gray-500 uppercase tracking-widest border-b pb-4 mb-6">GDPR, CCPA, KVKK & BIPA Compliant</p>

                        <h2 className="text-xl font-bold text-black mt-6">1. What We Collect (Biometric & Scan Data — BIPA / GDPR / KVKK)</h2>
                        <p>Skinface AI uses your device camera to capture short scans and to map 468 geometric facial landmarks (Face Mesh) required to calculate skin and structural metrics. To run analysis, generate insights, and let you compare your progress over time, the following are processed and — when you are signed in — stored on our servers (Supabase) tied to your account:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li><strong>Scan image (`image_url`):</strong> the still image captured during a scan, stored against your account so we can render your dashboard, before/after, and share cards.</li>
                            <li><strong>Derived face state (`face_state`):</strong> a stabilized, multi-frame numerical representation of your scan (landmarks, region metrics, color/texture vectors). It is required to recompute scores and to power trend analysis between scans.</li>
                            <li><strong>Analysis results & recommendations:</strong> the structured scores, insights, and routine suggestions produced from each scan.</li>
                            <li><strong>Account profile:</strong> email, age range, gender preference (used to personalize tone and recommendations), and subscription state.</li>
                        </ul>
                        <p className="mt-2">If you use the app as a <strong>guest</strong>, scans stay only on your device's local storage and are never uploaded.</p>

                        <h2 className="text-xl font-bold text-black mt-6">2. Retention</h2>
                        <p>We retain your scan image, face state, analysis results, and recommendations <strong>for as long as your account exists</strong>. There is no automatic time-based deletion: your scan history is intentionally preserved so progress tracking and longitudinal insights stay accurate. When you delete your account (see Section 4), all of the above are removed from our active systems.</p>

                        <h2 className="text-xl font-bold text-black mt-6">3. Third-Party Intelligence Processing</h2>
                        <p>To generate personalized routines and insights, sanitized numerical metrics (e.g., region-level scores, no raw images and no PII) are transmitted via encrypted connection to our AI provider through our backend proxy (Google Gemini, routed via our server). This data is used strictly for one-time inference for your account and is <strong>categorically prohibited from being used to train third-party AI models.</strong></p>

                        <h2 className="text-xl font-bold text-black mt-6">4. Your Rights — Access, Export, and Deletion</h2>
                        <p>Under GDPR, CCPA, KVKK, and equivalent laws you retain full sovereignty over your data:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li><strong>Right to access / export:</strong> contact <a href="mailto:support@skinface.ai" className="underline">support@skinface.ai</a> to request a copy of your scans, derived face state, and recommendations.</li>
                            <li><strong>Right to deletion ("Right to be Forgotten"):</strong> use the <strong>Delete Account</strong> button in the in-app menu. This irreversibly removes your scan images, derived face states, analysis results, recommendations, and your profile row.</li>
                            <li><strong>Authentication record:</strong> for fraud and abuse prevention, the auth credentials row (your email + login metadata) may be removed asynchronously after deletion is requested. If you need an immediate auth-row purge, email <a href="mailto:support@skinface.ai" className="underline">support@skinface.ai</a> and we will action it manually.</li>
                        </ul>

                        <h2 className="text-xl font-bold text-black mt-6">5. Strict Zero-Sale Policy</h2>
                        <p>Skinface AI operates on a subscription-based business model. We do not sell, trade, or broker your personal email, scan data, metrics, or usage behavior to any advertising networks or third-party data brokers.</p>
                    </div>
                )}

                {activeTab === 'medical' && (
                    <div className="space-y-5">
                        <h1 className="text-3xl font-extrabold text-black mb-2">Strict Medical Disclaimer</h1>
                        <p className="text-xs text-gray-500 uppercase tracking-widest border-b pb-4 mb-6">Assumption of Risk</p>
                        
                        <div className="p-5 bg-red-50 text-red-900 border border-red-200 rounded-xl shadow-sm">
                            <h2 className="font-bold flex items-center gap-2 mb-2">
                                <svg className="w-5 h-5 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                                </svg>
                                NOT A MEDICAL DEVICE
                            </h2>
                            <p className="text-sm leading-relaxed">By utilizing Skinface AI, you legally acknowledge that this application is designed <strong>EXCLUSIVELY for cosmetic, aesthetic tracking, and entertainment purposes.</strong> It is not intended for use in the diagnosis, cure, mitigation, treatment, or prevention of any disease or dermatological condition.</p>
                        </div>

                        <h2 className="text-xl font-bold text-black mt-6">1. No Dermatological Diagnosis</h2>
                        <p>While artificial intelligence may identify visual manifestations such as dark spots, textural flaws, or potential UV damage, these are purely pixel-based aesthetic estimations. <strong>Skinface AI cannot and does not diagnose melanoma, cystic acne, rosacea, or any other pathological skin diseases.</strong> You must consult a board-certified dermatologist for any clinical concerns.</p>

                        <h2 className="text-xl font-bold text-black mt-6">2. Body Dysmorphia and Psychological Health</h2>
                        <p>Skinface AI provides highly detailed feedback on facial geometry, symmetry, and "attractiveness" scoring based on specific datasets. We acknowledge that physical cosmetic grading can be emotionally impactful.</p>
                        <p><strong>CRITICAL WARNING:</strong> If you suffer from or suspect you may be experiencing Body Dysmorphic Disorder (BDD), eating disorders, or any clinical anxiety related to your physical appearance, <strong>you are strongly advised to cease using this application immediately.</strong> Our algorithmic scores are not an absolute measure of human worth. Please seek support from a licensed mental health professional.</p>

                        <h2 className="text-xl font-bold text-black mt-6">3. Complete Release of Liability</h2>
                        <p>You assume full and unwavering responsibility for your interpretation and use of the application's output. Skinface AI shall bear zero liability for any psychological distress, misdiagnosis, allergic reactions to skincare recommendations, or self-esteem impacts stemming from this software.</p>
                    </div>
                )}
            </main>
        </div>
    );
};

export default LegalModal;
